export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-normal font-[family-name:var(--font-fraunces)] text-[#1f2a24] mb-8">
        About ClaimBack
      </h1>

      <div className="prose max-w-none">
        <section className="mb-12">
          <h2 className="text-xl font-normal font-[family-name:var(--font-fraunces)] text-[#1f2a24] mb-4">
            What is this?
          </h2>
          <p className="font-light text-[#5c6b62] leading-[1.7] mb-4">
            ClaimBack is a free, open-source tool that helps Americans fight
            unfair medical bills. It generates dispute letters and teaches you
            the legal rights that the healthcare billing system is designed to
            hide from you.
          </p>
          <p className="font-light text-[#5c6b62] leading-[1.7]">
            The tool is entirely deterministic: no AI, no accounts, no
            tracking. It uses decision trees and letter templates based on
            actual federal and state laws to generate documents you can send to
            providers, insurers, and debt collectors.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-xl font-normal font-[family-name:var(--font-fraunces)] text-[#1f2a24] mb-4">
            Why does this exist?
          </h2>
          <p className="font-light text-[#5c6b62] leading-[1.7] mb-4">
            The American healthcare billing system is built on information
            asymmetry. Insurance companies and hospitals have teams of
            specialists who know every billing code, every loophole, and every
            legal technicality. Patients get a confusing bill and are expected
            to just pay it.
          </p>
          <p className="font-light text-[#5c6b62] leading-[1.7]">
            ClaimBack exists to close that gap. Every letter this tool generates
            cites the same laws and regulations that the industry uses,
            but puts them in the hands of patients.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-xl font-normal font-[family-name:var(--font-fraunces)] text-[#1f2a24] mb-4">
            Privacy
          </h2>
          <p className="font-light text-[#5c6b62] leading-[1.7] mb-4">
            ClaimBack is a static website. There is no server. There is no
            database. There are no user accounts. There is no analytics tracking.
          </p>
          <p className="font-light text-[#5c6b62] leading-[1.7]">
            Everything you enter stays in your browser&apos;s local storage. When
            you generate a letter, it is rendered entirely on your device. No
            data is ever transmitted to us or anyone else. You can verify this
            yourself. The entire source code is open source.
          </p>
        </section>

        <section className="bg-[#faf3e8] border border-[#e2ddd3] rounded-[14px] p-6">
          <h2 className="text-xl font-normal font-[family-name:var(--font-fraunces)] text-[#7a5c28] mb-4">
            Legal Disclaimer
          </h2>
          <p className="text-[#7a5c28] font-semibold mb-4">
            <strong>
              This tool provides general information about legal rights. It is
              not legal advice and does not create an attorney-client
              relationship.
            </strong>
          </p>
          <p className="font-light text-[#876025] mb-4">
            The information provided by ClaimBack is for general informational
            and educational purposes only. It is not a substitute for
            professional legal advice. Laws vary by state and change over time.
            The legal citations in this tool were accurate as of their last
            verification date, but may have been amended or superseded.
          </p>
          <p className="font-light text-[#876025] mb-4">
            Letters generated by this tool have not been reviewed by an
            attorney. While they cite real statutes and regulations, their
            applicability to your specific situation may vary.
          </p>
          <p className="font-light text-[#876025]">
            For advice about your specific situation, consult a licensed
            attorney or contact your state&apos;s legal aid organization. Many
            legal aid organizations provide free assistance for medical billing
            disputes.
          </p>
        </section>
      </div>
    </div>
  );
}
