/**
 * Letter templates as string constants.
 * These are Handlebars templates that get compiled and rendered client-side.
 *
 * We store them as TypeScript string exports rather than .hbs file imports
 * to avoid bundler configuration issues (Turbopack vs webpack).
 * The .hbs files are kept as the source-of-truth for editing.
 */

export const templates: Record<string, string> = {
  "itemized-bill-request": `<div style="font-family: 'Times New Roman', Times, serif; font-size: 12pt; line-height: 1.6; max-width: 8.5in; margin: 0 auto;">

<p>{{senderName}}<br>
{{senderStreet}}<br>
{{senderCity}}, {{senderState}} {{senderZip}}</p>

<p>{{today}}</p>

<p>{{providerName}}<br>
{{#if billingDepartment}}{{billingDepartment}}<br>{{/if}}
{{providerStreet}}<br>
{{providerCity}}, {{providerState}} {{providerZip}}</p>

<p><strong>Re: Request for Itemized Bill</strong><br>
Patient: {{senderName}}<br>
{{#if accountNumber}}Account Number: {{accountNumber}}<br>{{/if}}
Date(s) of Service: {{formatDate dateOfService}}<br>
Amount Billed: {{formatCurrency billAmount}}</p>

<p>Dear Billing Department:</p>

<p>I am writing to request a complete itemized bill for the medical services referenced above. I received a summary statement showing a total balance of {{formatCurrency billAmount}}, but I have not received a detailed breakdown of individual charges.</p>

<p>I am requesting an itemized statement that includes:</p>

<ol>
<li>Each individual charge listed separately with its corresponding CPT/HCPCS billing code</li>
<li>A description of each service, procedure, or supply</li>
<li>The date each service was provided</li>
<li>The name and credentials of the provider who rendered each service</li>
<li>The quantity and unit price for each item</li>
<li>Any adjustments, discounts, or insurance payments applied</li>
</ol>

<p>This request is made pursuant to my rights as a patient to receive a detailed accounting of charges for services rendered. Federal regulations and most state consumer protection laws require healthcare providers to furnish itemized bills upon patient request.</p>

<p>Please provide this itemized statement within 30 days of receipt of this letter. I am sending this letter via certified mail to document my request and establish a record of the date it was received.</p>

<p>Please do not take any collection action, including reporting to credit bureaus, while this request is being processed. I am not disputing the debt at this time; I am exercising my right to receive a complete accounting of charges before making payment arrangements.</p>

<p>Please send the itemized statement to the address listed above. If you have any questions, you may contact me at the address above.</p>

<p>Sincerely,</p>

<br><br>

<p>{{senderName}}</p>

<br>

<p style="font-size: 10pt; font-style: italic;">Sent via USPS Certified Mail, Return Receipt Requested</p>

<hr style="margin-top: 2em; border: none; border-top: 1px solid #ccc;">
<p style="font-size: 9pt; color: #666; font-style: italic;">This letter was generated by ClaimBack (claimback.org), a free educational tool. It has not been reviewed by an attorney. The information provided is for general informational purposes only and does not constitute legal advice.</p>

</div>`,

  "charity-care-application": `<div style="font-family: 'Times New Roman', Times, serif; font-size: 12pt; line-height: 1.6; max-width: 8.5in; margin: 0 auto;">

<p>{{senderName}}<br>
{{senderStreet}}<br>
{{senderCity}}, {{senderState}} {{senderZip}}</p>

<p>{{today}}</p>

<p>{{providerName}}<br>
{{#if billingDepartment}}{{billingDepartment}}<br>{{/if}}
{{providerStreet}}<br>
{{providerCity}}, {{providerState}} {{providerZip}}</p>

<p><strong>Re: Request for Financial Assistance Review</strong><br>
Patient: {{senderName}}<br>
{{#if accountNumber}}Account Number: {{accountNumber}}<br>{{/if}}
Date(s) of Service: {{formatDate dateOfService}}<br>
Amount Billed: {{formatCurrency billAmount}}</p>

<p>Dear Patient Financial Services:</p>

<p>I am writing to formally request a review of my eligibility for financial assistance under your hospital's Financial Assistance Policy (FAP). I have received a bill for {{formatCurrency billAmount}} for services provided on {{formatDate dateOfService}}, and I am unable to pay this amount based on my current financial circumstances.</p>

<p>My household financial information is as follows:</p>

<ul>
<li>Annual household income: {{formatCurrency annualIncome}}</li>
<li>Household size: {{householdSize}} person(s)</li>
</ul>

<p>I respectfully request the following:</p>

<ol>
<li>A determination of my eligibility for financial assistance under your FAP</li>
<li>A copy of your Financial Assistance Policy and application form, if one has not already been provided to me</li>
<li>A copy of your plain-language summary of the FAP</li>
<li>Information about any other discount programs, payment plans, or hardship programs that may be available</li>
</ol>

<p>Pursuant to Section 501(r) of the Internal Revenue Code, tax-exempt hospitals are required to maintain a Financial Assistance Policy and to make reasonable efforts to determine whether patients qualify for assistance before engaging in extraordinary collection actions, including reporting to credit bureaus, selling the debt, or pursuing legal action.</p>

<p>I am requesting that all collection activity on this account be suspended while my financial assistance application is under review. I am acting in good faith to resolve this balance and am providing my financial information for your review.</p>

<p>I understand that you may require supporting documentation. I am prepared to provide any necessary verification of my income and household size, including tax returns, pay stubs, or other documents as needed. Please let me know what documentation is required and I will submit it promptly.</p>

<p>Please respond to this request within 30 days at the address listed above. I am sending this letter via certified mail to document my request.</p>

<p>Thank you for your consideration.</p>

<p>Sincerely,</p>

<br><br>

<p>{{senderName}}</p>

<br>

<p style="font-size: 10pt; font-style: italic;">Sent via USPS Certified Mail, Return Receipt Requested</p>

<hr style="margin-top: 2em; border: none; border-top: 1px solid #ccc;">
<p style="font-size: 9pt; color: #666; font-style: italic;">This letter was generated by ClaimBack (claimback.org), a free educational tool. It has not been reviewed by an attorney. The information provided is for general informational purposes only and does not constitute legal advice.</p>

</div>`,

  "no-surprises-dispute": `<div style="font-family: 'Times New Roman', Times, serif; font-size: 12pt; line-height: 1.6; max-width: 8.5in; margin: 0 auto;">

<p>{{senderName}}<br>
{{senderStreet}}<br>
{{senderCity}}, {{senderState}} {{senderZip}}</p>

<p>{{today}}</p>

<p>{{providerName}}<br>
{{#if billingDepartment}}{{billingDepartment}}<br>{{/if}}
{{providerStreet}}<br>
{{providerCity}}, {{providerState}} {{providerZip}}</p>

<p><strong>Re: Dispute of Charges Exceeding Good Faith Estimate Under the No Surprises Act</strong><br>
Patient: {{senderName}}<br>
{{#if accountNumber}}Account Number: {{accountNumber}}<br>{{/if}}
Date(s) of Service: {{formatDate dateOfService}}</p>

<p>Dear Billing Department:</p>

<p>I am writing to formally dispute charges for medical services that substantially exceed the Good Faith Estimate (GFE) I was provided prior to my scheduled service.</p>

<p>The relevant figures are as follows:</p>

<ul>
<li>Good Faith Estimate provided: {{formatCurrency gfeAmount}}</li>
<li>Actual amount billed: {{formatCurrency billAmount}}</li>
<li>Difference: {{subtractCurrency billAmount gfeAmount}}</li>
</ul>

<p>Under the No Surprises Act (Public Law 116-260, Division BB, Title I) and its implementing regulations at 45 CFR Part 149, uninsured and self-pay patients who receive a Good Faith Estimate have the right to initiate a Patient-Provider Dispute Resolution (PPDR) process when the actual bill exceeds the GFE by $400 or more.</p>

<p>The difference between my GFE and the actual charges exceeds the $400 statutory threshold. I am therefore exercising my right to dispute these charges.</p>

<p>I am requesting the following:</p>

<ol>
<li>Initiation of the Patient-Provider Dispute Resolution process as provided under the No Surprises Act</li>
<li>An itemized explanation of all charges that differ from the Good Faith Estimate, including the reason for each difference</li>
<li>Immediate suspension of all collection activity on this account pending resolution of this dispute</li>
<li>Confirmation that this account will not be reported to any credit reporting agency while the dispute is pending</li>
</ol>

<p>Under the No Surprises Act, you are required to cease collection of the disputed amount while the dispute resolution process is underway. The dispute must be resolved by an independent dispute resolution entity, and the determination is binding.</p>

<p>This dispute is being filed within the 120-day window allowed by the statute. I am sending this letter via certified mail to document the date of my dispute.</p>

<p>Please respond to this letter within 15 business days with information on how the PPDR process will be initiated, or to resolve this matter directly.</p>

<p>Sincerely,</p>

<br><br>

<p>{{senderName}}</p>

<br>

<p style="font-size: 10pt; font-style: italic;">Sent via USPS Certified Mail, Return Receipt Requested</p>

<hr style="margin-top: 2em; border: none; border-top: 1px solid #ccc;">
<p style="font-size: 9pt; color: #666; font-style: italic;">This letter was generated by ClaimBack (claimback.org), a free educational tool. It has not been reviewed by an attorney. The information provided is for general informational purposes only and does not constitute legal advice.</p>

</div>`,

  "debt-validation-demand": `<div style="font-family: 'Times New Roman', Times, serif; font-size: 12pt; line-height: 1.6; max-width: 8.5in; margin: 0 auto;">

<p>{{senderName}}<br>
{{senderStreet}}<br>
{{senderCity}}, {{senderState}} {{senderZip}}</p>

<p>{{today}}</p>

<p>{{collectorName}}<br>
{{collectorStreet}}<br>
{{collectorCity}}, {{collectorState}} {{collectorZip}}</p>

<p><strong>Re: Demand for Debt Validation</strong><br>
{{#if referenceNumber}}Reference/Account Number: {{referenceNumber}}<br>{{/if}}
{{#if originalCreditor}}Original Creditor: {{originalCreditor}}<br>{{/if}}
Amount Claimed: {{formatCurrency amountClaimed}}</p>

<p>Dear Sir or Madam:</p>

<p>I am writing in response to your communication regarding the above-referenced account. Pursuant to my rights under the Fair Debt Collection Practices Act, 15 USC § 1692g, I am formally disputing this debt and demanding validation.</p>

<p>I am requesting that you provide the following information:</p>

<ol>
<li>The amount of the debt, including an itemized accounting of all charges, fees, interest, and payments</li>
<li>The name and address of the original creditor</li>
<li>A copy of any signed agreement or contract between me and the original creditor establishing the alleged obligation</li>
<li>Proof that you are licensed to collect debts in the state of {{senderState}}</li>
<li>Proof that the statute of limitations on this debt has not expired</li>
<li>A complete payment history showing all charges, credits, and payments from the original creditor to the present</li>
<li>Documentation showing the chain of assignment if this debt has been sold or transferred</li>
</ol>

<p>Under the FDCPA, you are required to cease all collection activity regarding this debt until you have provided adequate validation. Specifically:</p>

<ul>
<li>You may not continue to contact me regarding this debt until validation has been provided</li>
<li>You may not report this debt to any credit reporting agency until validation has been provided</li>
<li>If you have already reported this debt, you must notify the credit reporting agencies that the debt is disputed</li>
</ul>

<p>I am not acknowledging that I owe this debt. I am exercising my legal right to demand proof that the debt is valid, that the amount is correct, and that you have the legal authority to collect it.</p>

<p>If you cannot provide adequate validation of this debt, I demand that you cease all collection efforts and remove any negative reporting from my credit files.</p>

<p>Any continued collection activity or credit reporting without providing the requested validation will be considered a violation of the FDCPA, and I will not hesitate to pursue my rights under the statute, including the recovery of statutory damages, actual damages, and attorney's fees.</p>

<p>Please govern yourself accordingly.</p>

<p>Sincerely,</p>

<br><br>

<p>{{senderName}}</p>

<br>

<p style="font-size: 10pt; font-style: italic;">Sent via USPS Certified Mail, Return Receipt Requested</p>

<hr style="margin-top: 2em; border: none; border-top: 1px solid #ccc;">
<p style="font-size: 9pt; color: #666; font-style: italic;">This letter was generated by ClaimBack (claimback.org), a free educational tool. It has not been reviewed by an attorney. The information provided is for general informational purposes only and does not constitute legal advice.</p>

</div>`,
};
